# Generated by Django 5.0.6 on 2024-05-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=50)),
                ('imagen', models.ImageField(null=True, upload_to='')),
                ('descripcion', models.CharField(max_length=50)),
                ('valor', models.IntegerField()),
            ],
        ),
    ]
